language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '12'
script:
  - npm run build
after_success:
  -  cd dist && npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

