const overrides = ({ colors, sizes }) => {
  return {
    colors: {
      accent: colors.accent,
      primary: colors.primary,
      secondary: colors.secondary,
      inputBorderActive: colors.primary,
      inputEnhancerFillDisabled: colors.primary,
      inputBorder: '#CCC',
      inputFill: '#FFF',
      inputFillDisabled: '#FFF',

      inputBorderPositive: colors.primary,
      borderFocus: colors.primary,
      calendarDayBackgroundSelectedHighlighted: colors.primary,
      calendarDayForegroundPseudoSelected: colors.primary,
      calendarDayForegroundPseudoSelectedHighlighted: colors.primary,
      calendarDayForegroundSelected: colors.primary,
      calendarHeaderBackground: colors.primary,
      calendarHeaderBackgroundActive: colors.primary,
      tagPrimarySolidBackground: colors.primary,
    },
    borders: {
      border100: {
        borderColor: colors.primary,
        borderStyle: 'solid',
        borderWidth: '1px',
      },
      border200: {
        borderColor: colors.primary,
        borderStyle: 'solid',
        borderWidth: '1px',
      },
      border300: {
        borderColor: colors.primary,
        borderStyle: 'solid',
        borderWidth: '1px',
      },
      border400: {
        borderColor: colors.primary,
        borderStyle: 'solid',
        borderWidth: '1px',
      },
      border500: {
        borderColor: colors.primary,
        borderStyle: 'solid',
        borderWidth: '1px',
      },
      border600: {
        borderColor: colors.primary,
        borderStyle: 'solid',
        borderWidth: '1px',
      },
      buttonBorderRadius: '0px',
      inputBorderRadius: `${sizes.borderRadius}px`,
      popoverBorderRadius: `${sizes.borderRadius}px`,

      radius100: '2px',
      radius200: '4px',
      radius300: '8px',
      radius400: '12px',
      surfaceBorderRadius: `${sizes.borderRadius}px`,
      useRoundedCorners: true,
    },

    sizing: {
      scale0: '2px',
      scale100: '4px',
      scale200: '6px',
      scale300: '8px',
      scale400: '9px',
      scale500: '12px',
      scale550: '14px',
      scale600: '16px',
      scale650: '18px',
      scale700: '20px',
      scale750: '22px',
      scale800: '24px',
      scale900: '32px',
      scale1000: '40px',
      scale1200: '48px',
      scale1400: '56px',
      scale1600: '64px',
      scale2400: '96px',
      scale3200: '128px',
      scale4800: '192px',
    },
  };
};
export default overrides;
